### ISSUE TITLE
When Sampling, Summary Statistics not showing

### ISSUE THREAD

**Issue by AlessioPop** [sefffal/DirectDetections.jl#10]
![help](https://user-images.githubusercontent.com/120112894/206470573-f3e38ecf-f0eb-4dda-9a66-e72fde38b0b0.PNG)

**Comment by sefffal** [comment]
Hi @AlessioPop 
The semicolon you added at the end suppressed the output.
You can show it by removing the semi colon or by typing `chain` in a new cell and running it.
